### ISSUE TITLE
Please document importance of module

### ISSUE THREAD

**Issue by pyhedgehog** [JyJyJcr/ngx-strict-sni#1]
What's difference from
```
map $http_host $sni_strict {
$ssl_server_name 1;
default 0;
}
if($sni_strict = 0) {
return 421;
}
```

**Comment by JyJyJcr** [comment]
Practically, these two conf files will behave the same way; both will reject SNI/Host inconsistencies with return code 421.
- use `map` and `if` as your snippet do (I didn't actually try to run):

```
http {
    ...
    map $http_host $sni_strict {
        $ssl_server_name 1;
        default 0;
    }
    server aaa.example.com {
        ...
        if($sni_strict = 0) {
            return 421;
        }
    }
    server bbb.example.com {
        ...
        if($sni_strict = 0) {
            return 421;
        }
    }
}
```

- use this module:

```
http {
    ...
    strict_sni on;
    server aaa.example.com {
        ...
        // no directive
    }
    server bbb.example.com {
        ...
        // no directive
    }
}
```

Nevertheless, this module has advantages listed below:

## Remove duplication of the snippet

Since `if` directive is not allowed in `http` context, you must write the filter in every server context.
This module's filter logic is automatically registered in every `http`, `server`, `location` context, and then it inherits parent settings (in parent context). Therefore you only have to write the directive once.
This is useful to avoid human error.

## Remove `if` directive

[As the official document said (for unknown reason they deleted it!)](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/), `if` behaves tricky, especially in `location`. This module removes `if` describing the filter, resulting to simplify the control flow.

## Flexible configuration

It is troublesome to filter in almost all locations and not to filter in specific location, because the `if` directive filter is inherited to child context. Using the module you can easily configure this, as shown in [README](https://github.com/JyJyJcr/ngx-strict-sni?tab=readme-ov-file#use-case).
